config/routes.rb
Rails.application.routes.draw do
  get    "/auth/github/callback", to: "sessions#create"
  get    "/auth/github", as: :login
  delete "/logout",  to: "sessions#destroy"

  get  '/dashboard', to: 'dashboard#show'

  root "stats#index"
  resources :stats, only: [:show]
end

app/models/github.rb
class Github

  attr_reader :user, :service

  def initialize(user)
    @service ||= GithubService.new(user)
    @user    ||= user
  end

  def repos
    repos = service.find_user_repos(user).map {|data| build_object(data)}
    repo_name = repos.map {|repo| repo.name }
    repo_name
  end

  def followers
    list = service.find_followers(user).map {|data| build_object(data)}
    followers = list.map {|follower| follower.login}
    followers
  end

  def followees
    list = service.find_user_follows(user).map {|data| build_object(data)}
    followees = list.map {|followee| followee.login}
    followees
  end

  def organizations
    list = service.find_user_organizations(user).map {|data| build_object(data)}
    organizations = list.map {|organization| organization}
    organizations
  end

  private

  def build_object(data)
    OpenStruct.new(data)
  end
end

app/models/global_constants.rb
module GlobalConstants
   URLS = ["https://github.com/bad6e",
          "https://github.com/roseak",
          "https://github.com/mcschatz",
          "https://github.com/travishaby",
          "https://github.com/Jpease1020",
          "https://github.com/jphoenix86",
          "https://github.com/HoffsMH",
          "https://github.com/MowAlon",
          "https://github.com/russelleh",
          "https://github.com/jbrr",
          "https://github.com/rasensio1",
          "https://github.com/selfup",
          "https://github.com/dastinnette",
          "https://github.com/mbburch",
          "https://github.com/Kealii",
          "https://github.com/Unsafepond",
          "https://github.com/ChrisCenatie",
          "https://github.com/adamki",
          "https://github.com/plato721",
          "https://github.com/Egogre"]


  USERS = %w(
              bad6e
              roseak
              mcschatz
              travishaby
              Jpease1020
              jphoenix86
              HoffsMH
              MowAlon
              russelleh
              jbrr
              rasensio1
              selfup
              dastinnette
              mbburch
              Kealii
              Unsafepond
              ChrisCenatie
              adamki
              plato721
              Egogre
            )
end

app/models/stat.rb
class Stat < ActiveRecord::Base
  validates :name, presence: true

  def when_created
    created_at.strftime("%A, %B %d, %Y at %I:%M%p")
  end

  def self.commit_order
    order(commits: :desc)
  end

  def self.current_streak
    order(current_streaks: :desc)
  end

  def self.streak
    order(streaks: :desc)
  end

  def self.updated_at
    first.when_created
  end

  def self.name_list
    order(name: :asc)
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.find_or_create_from_oauth(oauth)
    user = User.find_or_create_by(provider: oauth.provider, uid: oauth.uid)
    user.email              = oauth.info.email
    user.nickname           = oauth.info.nickname
    user.image_url          = oauth.info.image
    user.token              = oauth.credentials.token
    user.repos              = GithubPresenter.new(user).repos
    user.starred_repos      = GithubPresenter.new(user).starred_repos
    user.organizations      = GithubPresenter.new(user).organizations
    user.commit_messages    = GithubPresenter.new(user).commit
    user.followers          = GithubPresenter.new(user).followers
    user.followees          = GithubPresenter.new(user).followees
    user.total_commits      = GithubPresenter.new(user).year_commits
    user.current_streak     = GithubPresenter.new(user).current_streaks
    user.longest_streak     = GithubPresenter.new(user).longest_streaks
    user.follower_messages  = GithubPresenter.new(user).followers_activities
    user.save

    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  include SessionsHelper
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @current_user
    @user_info  ||= UserPresenter.new(current_user)
    @stats      ||= StatsPresenter.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_oauth(oauth)

    if @user
      log_in(@user)
      redirect_to dashboard_path
    else
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private

    def oauth
      request.env['omniauth.auth']
    end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController

  def index
    @stats = StatsPresenter.new
  end

  def show
    @stats     = StatsPresenter.new
    @stat_user = Stat.find(params[:id])
  end

  private

  def commit_params
    params.require(:stat).permit(:name, :commits, :streaks, :current_streaks, :commit_messages)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = @user.id
  end
end

app/views/dashboard/show.html.erb
<div class="container-fluid container-home">
  <div class="col-md-12">
    <h1 class="home">You Are Authorized</h1>
    <%= image_tag current_user.image_url, class: "img-circle img-thumbnail home-image" %>
    <h3 class="home"> <%= current_user.nickname %> </h2>
    <h2 class="home"> <%= current_user.email %> </h2>
    <h4 class="home"><%= pluralize(@user_info.starred_repos, 'Repository')%> Starred</h4>
    <%= link_to "Logout", logout_path, method: :delete, class: "btn btn-lg btn-default btn-home" %>
    <h2 class="home" id="contrib-sum"> Contribution Summary</h2>

    <button class="btn btn-lg btn-default btn-home" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      Click Here for Stats
    </button>

    <div class="collapse" id="collapseExample">
      <div class="col-md-4 home">
        <h4>Total Commits</h4>
        <p><%= @user_info.year_commits %></pr>
      </div>
      <div class="col-md-4 home">
        <h4>Current Streak</h4>
        <p><%= @user_info.current_streaks %></pr>
      </div>
      <div class="col-md-4 home">
        <h4>Longest Streak</h4>
        <p><%= @user_info.longest_streaks %></pr>
      </div>
    </div>

  <div class"container">
    <div class="row">
      <br>

      <div class="col-md-4">
        <h3 class="home">Your Repositories</h3>
        <br>
        <table class="table home">
          <thead>
            <tr>
              <th>Repo Name</th>
            </tr>
          </thead>
          <% @user_info.repos.each do |repo| %>
            <tr>
              <td><%= repo %></td>
            </tr>
          <% end %>
        </table>
      </div>

      <div class="col-md-4">
        <h3 class="home">Your Followers</h3>
        <br>
        <table class="table home">
          <thead>
            <tr>
              <th>Who is Following You</th>
            </tr>
          </thead>
          <% @user_info.followers.each do |follower| %>
            <tr>
              <td><%= follower %></td>
            </tr>
          <% end %>
        </table>
      </div>

      <div class="col-md-4">
        <h3 class="home">Who You are Following?</h3>
        <br>
        <table class="table home">
          <thead>
            <tr>
              <th>Who You are Following</th>
            </tr>
          </thead>
          <% @user_info.followees.each do |followee| %>
            <tr>
              <td ><%= followee %></td>
            </tr>
          <% end %>
        </table>
      </div>

    </div>
  </div>

  <div class"container">
    <div class="row">

      <div class="col-md-4">
        <h3 class="home">Your Organizations</h3>
        <br>
        <% @user_info.organizations.each do |org| %>
          <p class="home"><%= org %></p>
        <% end %>
      </div>

      <div class="col-md-4">
        <h3 class="home">Your Recent Commit Messages</h3>
        <% @user_info.commit_mess.each do |message| %>
        <p class="home"><%= message %></p>
        <% end %>
      </div>

      <div class="col-md-4">
        <h3 class="home">Summary Feed of my Followers</h3>
        <% @user_info.followers_activities.each do |activity| %>
          <p class="home"><%= activity %></p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <br>
    <h3 class="home">1507 Git Statistics</h3>
    <br>
    <button class="btn btn-lg btn-default btn-home button1">See Statistics</button>
    <br><br>
  </div>
  <%= render partial: "layouts/stat_board" %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="row">
    <div class="col-md-12">
      <p>Copyright &copy; The Sweater 2015</p>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Git Commit</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Individual Commit Messages <span class="caret"></span></a>
          <ul class="dropdown-menu">
           <% @stats.list_names.each do |stat| %>
            <li><%= link_to stat.name, stat_path(stat) %></li>
          <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_stat_board.html.erb
<div class="container commits" id="commits" style="display: none">

    <div class="col-md-4" align="center">
      <h3 class="home">Leaderboard</h3>
        <table class="table home">
          <tr>
            <th>Name</th>
            <th>Commits Since <%= Time.now.month %>/<%= Time.now.day %>/<%= Time.now.year - 1 %></th>
          </tr>
          <% @stats.ordered_commits.each do |stat| %>
          <tr>
            <td><%= stat.name %></td>
            <td><%= stat.commits %></td>
          </tr>
        <% end %>
      </table>
    </div>

  <div class="col-md-4" align="center" id="completed-orders">
    <h3 class="home">Current Streak</h3>
      <table class="table home">
        <tr>
          <th>Name</th>
          <th>Current Streak</th>
        </tr>
        <% @stats.current_streak.each do |streak| %>
        <tr>
          <td><%= streak.name %></td>
          <td><%= streak.current_streaks %></td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="col-md-4" align="center" id="completed-orders">
    <h3 class="home">Longest Streak</h3>
      <table class="table home">
        <tr>
          <th>Name</th>
          <th>Longest Streak</th>
        </tr>
        <% @stats.longest_streak.each do |streak| %>
        <tr>
          <td><%= streak.name %></td>
          <td><%= streak.streaks %></td>
        </tr>
      <% end %>
    </table>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gitcommit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "layouts/navbar" %>
    <%= yield %>
  <%= render partial: "layouts/footer" %>
</body>
</html>

app/views/stats/index.html.erb
<div class="container-fluid container-home">
  <div class="col-md-12">
   <h1 class="home">Welcome to the Git Commit Tracker</h1>
    <h2 class="home">A Personalized Github Tracker.</h2>
    <%= link_to "Login with Github", login_path, class: "btn btn-lg btn-default btn-home" %>
  </div>
  <br><br>

  <div class="col-md-12">
    <br>
    <h3 class="home">1507 Git Statistics</h3>
    <br>
    <button class="btn btn-lg btn-default btn-home button1">See Statistics</button>
    <br><br>
  </div>
  <%= render partial: "layouts/stat_board" %>
</div>

app/views/stats/show.html.erb
<div class="container-fluid container-home">
  <div class="col-md-12">
    <h1 class="home"><%= @stat_user.name %>'s Recent Commit Messages</h1>
    <%= link_to "Return Home", root_path, class: "btn btn-lg btn-default btn-home" %>
  </div>


  <div class="col-md-4 col-md-offset-4" align="center" id="completed-orders">
    <br><br>
    <h4 class="home">Recent Messages</h4>
      <table class="table home">
        <tr>
          <th>Message</th>
        </tr>
        <%@stats.commit_messages(@stat_user).each do |message|%>
          <tr>
            <td><%= message %></td>
          </tr>
        <% end %>
      </table>
  </div>

  <div class="container">
    <div class="col-md-12">
     <%= link_to "Login with Github", login_path, class: "btn btn-lg btn-default btn-home" %>
   </div>
  </div>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="">
      <meta name="author" content="">

      <title>1507 Git Commit Race</title>

      <!-- Bootstrap Core CSS -->
      <link href="css/bootstrap.min.css" rel="stylesheet">

      <!-- Custom CSS -->
      <style>
      body {
          padding-top: 70px;
          /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
      }
      </style>

      <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
      <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->

  </head>

  <body>

      <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">1507 Git Commit</a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>

      <!-- Page Content -->
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h1>1507 Git Commit Race</h1>
              <p class="lead">Compete with the best - who will have the most commits when Turing is over?</p>
            </div>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row well">
          <div class="col-md-offset-4 col-md-4 ">
            <h3 id="leaderboard">Leaderboard</h3>
              <table class="table">
                <tr>
                  <th>Place</th>
                  <th>Name</th>
                </tr>
                <% n = 0 %>
                <% @group.each do |css| %>
                  <tr>
                    <td><%= n = n + 1 %></td>
                    <td><%= css.join("- ") %> commits</td>
                  </tr>
                <% end %>
              <table>
          </div>
        </div>
      </div>
  </body>
</html>